### ISSUE TITLE
TextFormfield Autoselected Problem

### ISSUE THREAD

**Issue by Deatsilence** [Deatsilence/ZeroHunger#4]
while I was writing something on textfield, the sentence that ı wrote being full blue color.

![image](https://github.com/Deatsilence/ZeroHunger/assets/78795973/33407ea4-990b-4d34-a514-cf6a1863983c)

**Comment by cem256** [comment]
This is most likely caused by the autocorrect property of your TextFormField is set to true. As its explained [here](https://github.com/flutter/flutter/issues/55623#issuecomment-746325139) when the autocorrect is enabled it gives you word suggestions by highlighting the text. So setting it to false should resolve the problem

**Comment by Deatsilence** [comment]
> This is most likely caused by the autocorrect property of your TextFormField is set to true. As its explained [here](https://github.com/flutter/flutter/issues/55623#issuecomment-746325139) when the autocorrect is enabled it gives you word suggestions by highlighting the text. So setting it to false should resolve the problem

Thanks, the problem solved by you but if I wanna use autocomplate, what should I do ? Because email textformfield should remember email of users right ?

**Comment by cem256** [comment]
In that case you can use autofillHints property of the TextFormField without specifying the value of the autocorrect property. For example if you want to provide suggestions for emails you can use the following

> TextFormField(
      controller: controller,
      onChanged: onChanged,
      keyboardType: TextInputType.emailAddress,
      autofillHints: const [AutofillHints.email],
);

This will show suggestions for emails that are already logged into the device without highlighting the text

**Comment by Deatsilence** [comment]
> In that case you can use autofillHints property of the TextFormField without specifying the value of the autocorrect property. For example if you want to provide suggestions for emails you can use the following
> 
> > TextFormField(
> > controller: controller,
> > onChanged: onChanged,
> > keyboardType: TextInputType.emailAddress,
> > autofillHints: const [AutofillHints.email],
> > );
> 
> This will show suggestions for emails that are already logged into the device without highlighting the text

Thanks my friend
